/*
   Pins
*/
#define PIN_LED_GREEN 2
#define PIN_LED_RED 4
#define PIN_LED_YELLOW 3
#define PIN_LOAD_CELL_BACK 1
#define PIN_LOAD_CELL_CS 9
#define PIN_LOAD_CELL_FRONT 0
#define PIN_LOAD_CELL_RESET 7
#define PIN_LOAD_CELL_START 8
#define PIN_MOTOR A0
#define PIN_REMOTE_ACCELERATOR A1
#define PIN_SPI_LOAD_CELL_MISO 12
#define PIN_SPI_LOAD_CELL_MOSI 11
#define PIN_SPI_LOAD_CELL_SCK 13
#define PIN_WIFI 8,7,4,2
